# This file was generated by GoReleaser. DO NOT EDIT.
cask "noctra" do
  version "0.40.1"

  on_macos do
    on_intel do
      sha256 "0de20874ae281682dd34654495b6c8e00382ec965264d939bd691d658147d72b"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c4273506bfff4e3dc003ce7fe0f4fe87235e41bff9878a580bb5f93c791d5e2"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "859882b7351d80365fa5233a2cdd844689b9649a885c61033da5444a3d205416"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9fa5ae0da7e9d127142e020a09f75aa01826518e28a1f7556878cb09a2e13f8c"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "noctra"
  desc "Autonomous Linear-to-PR agent — polls Linear for tickets, implements them with Claude Code or OpenAI Codex, and creates pull requests."
  homepage "https://getnoctra.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noctra"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noctra"]
    end
  end

  # No zap stanza required

end
