# This file was generated by GoReleaser. DO NOT EDIT.
cask "noctra" do
  version "0.41.2"

  on_macos do
    on_intel do
      sha256 "e14fd38731d61d05eb543d218daa69b65942fec035bc7c64ea70e29fad6c5743"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8356d8800269b13ded0b3e682fa028923fa369cd3df6857b55b45a218733329a"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "46ed19883c18b5c208a56c3c31c12774d7b3fc673b07756eac017a1a6372c31f"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d32167f4be6273ced200df85c8fd318c69d41c7bd5ee2cff4e21c63933789489"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "noctra"
  desc "Autonomous Linear-to-PR agent — polls Linear for tickets, implements them with Claude Code or OpenAI Codex, and creates pull requests."
  homepage "https://getnoctra.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noctra"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noctra"]
    end
  end

  # No zap stanza required

end
