# This file was generated by GoReleaser. DO NOT EDIT.
cask "noctra" do
  version "0.46.0"

  on_macos do
    on_arm do
      sha256 "acd35c1e2e8fc22ba1a5ccfdc257002a4542255683c66a1297f4b9ea2b5a839e"
      url "https://github.com/onelastcommit/noctra/releases/download/v#{version}/noctra_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "834740d21c3f84bc32a93ad13750cfd3aad83d4a602fe260b314e6c20057ab85"
      url "https://github.com/onelastcommit/noctra/releases/download/v#{version}/noctra_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "80cce31fc726dc3becc176b61e9cdcb4299f69c341f648209f9a0fcc0095b0d0"
      url "https://github.com/onelastcommit/noctra/releases/download/v#{version}/noctra_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "37c72e90d359c37fcafcc2d768fd286737cfbfb3f3f6363702c39f7a075bb4a9"
      url "https://github.com/onelastcommit/noctra/releases/download/v#{version}/noctra_#{version}_linux_amd64.tar.gz"
    end
  end

  name "noctra"
  desc "Autonomous Linear-to-PR agent — polls Linear for tickets, implements them with Claude Code or OpenAI Codex, and creates pull requests."
  homepage "https://getnoctra.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noctra"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noctra"]
    end
  end

  # No zap stanza required
end
